- name: Copying MongoDB repo file
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: installing MongoDB
  ansible.builtin.yum:
    name: mongodb-org
    state: installed

- name: Update mongodb configuration
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start the mongodb service
  ansible.builtin.service:
    name: mongod
    state: started
    enabled: yes

#- name: download and unarchive
# ansible.builtin.unarchive:
#    src: https://github.com/stans-robot-project/mongodb/archive/main.zip
#    dest: /tmp
#   remote_src: yes

- name: Download and unarchive
  ansible.builtin.include_role:
    name: common
    tasks_from: download

- name: Load the files to Schema
  community.mongodb.mongodb_shell:
    file: "/tmp/mongodb-main/{{item}}.js"
    idempotent: yes
  loop:
    - catalogue
    - users

- name: Setting up hostname
  ansible.builtin.include_role:
    name: common
    tasks_from: set-hostname
    