- name: Copying the systemd file
  ansible.builtin.copy:
    src: systemd.service
    dest: /etc/systemd/system/{{COMPONENT}}.service

- name: Restart the service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: true
    name: "{{COMPONENT}}"
    enabled: true